# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm publish

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write
jobs:
    publish:
        # needs: prev-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Check the version
              id: check
              run: |
                  CURRENT_VERSION=$(jq -r .version package.json)
                  echo "Current version: $CURRENT_VERSION"
                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  echo "Latest tag: $LATEST_TAG"

                  LATEST_VERSION=${LATEST_TAG#v}

                  if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ];
                  then
                  echo "Version changed"
                  echo "version_changed=true" >> $GITHUB_OUTPUT
                  echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
                  else
                  echo "Version not changed"
                  echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Release version on GitHub
              if: steps.check.outputs.version_changed == 'true'
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ github.token }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    "https://api.github.com/repos/${{ github.repository }}/releases" \
                    -d '{"tag_name":"v${{ steps.check.outputs.new_version }}","target_commitish":"main","name":"v${{ steps.check.outputs.new_version }}","body":"Automatic release for version ${{ steps.check.outputs.new_version }}","draft":false,"prerelease":false,"generate_release_notes":true}'

            - name: Publish to NPM
              if: steps.check.outputs.version_changed == 'true'
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
