# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm publish

on:
    push:
        branches:
            # - main
            - dev1

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    publish:
        # needs: prev-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # - name: Check the version
            #   id: version
            #   run: |
            #       CURRENT_VERSION=$(jq -r .version package.json)
            #       echo "Current version: $CURRENT_VERSION"

            #       LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            #       echo "Latest tag: $LATEST_TAG"

            #       LATEST_VERSION=${LATEST_TAG#v}

            #       if [ "$LATEST_VERSION" != "$CURRENT_VERSION" && "$LATEST_VERSION" != "v0.0.0" ];
            #       then
            #       echo "Version changed"
            #       else
            #       echo "Version not changed"
            #       exit 1
            #       fi

            - name: Check NPM Token
              # id: check_token
              run: |
                  if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
                    echo "NPM_TOKEN is not set"
                    exit 1
                  else
                    echo "NPM_TOKEN is set"
                  fi

            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  target-branch: ${{ github.ref_name }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Publish to NPM
              if: ${{ steps.release.outputs.release_created }}
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
