# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm publish

on:
    # release:
    #     types: [created]
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    attestations: write # need?

jobs:
    publish:
        # needs: prev-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Check the version
              id: check
              run: |
                  CURRENT_VERSION=$(jq -r .version package.json)
                  echo "Current version: $CURRENT_VERSION"
                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  echo "Latest tag: $LATEST_TAG"

                  LATEST_VERSION=${LATEST_TAG#v}

                  if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ];
                  then
                  echo "Version changed"
                  echo "version_changed=true" >> $GITHUB_OUTPUT
                  echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
                  else
                  echo "Version not changed"
                  echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Release version on GitHub
              run: |
                  git tag -a "v${{ steps.check.outputs.new_version }}" -m "v${{ steps.check.outputs.new_version }}"
                  git push origin "v${{ steps.check.outputs.new_version }}"

            - name: Publish to NPM
              if: steps.check.outputs.version_changed == 'true'
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
