# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
    push:
        branches:
            - main

jobs:
    publish:
        # needs: prev-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 17
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Check the version
              id: check
              run: |
                  CURRENT_VERSION=$(jq -r .version package.json)
                  echo "Current version: $CURRENT_VERSION"
                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  echo "Latest tag: $LATEST_TAG"

                  LATEST_VERSION=${LATEST_TAG#v}

                  if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; 
                  then
                  echo "Version changed"
                  echo "version_changed=true" >> $GITHUB_OUTPUT
                  echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
                  else
                  echo "Version not changed"
                  echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            # - name: Publish to NPM
            #   run: npm publish
            #   env:
            #       NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Tag release
              if: steps.check.outputs.version_changed == 'true'
              run: |
                  echo "github.EMAIL: ${{ github.EMAIL }}"
                  echo "github.NAME: ${{ github.NAME }}"

                  echo "env.EMAIL: ${{ env.EMAIL }}"
                  echo "env.NAME: ${{ env.NAME }}"

                  echo "secrets.EMAIL: ${{ secrets.EMAIL }}"
                  echo "secrets.NAME: ${{ secrets.NAME }}"

                  git config --local user.email "belartale@gmail.com"
                  git config --local user.name "belartale"
                  git tag -a "v${{ steps.check.outputs.new_version }}" -m "v${{ steps.check.outputs.new_version }}"
                  git push origin "v${{ steps.check.outputs.new_version }}"
