# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm publish

on:
    push:
        branches:
            # - main
            - dev1

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    check-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Check the version
              id: version
              run: |
                  CURRENT_VERSION=$(jq -r .version package.json)
                  echo "Current version: $CURRENT_VERSION"

                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                  echo "Latest tag: $LATEST_TAG"

                  LATEST_VERSION=${LATEST_TAG#v}

                  if [ -z "$LATEST_VERSION" != "$CURRENT_VERSION" ];
                  then
                  echo "Version changed"
                  else
                  echo "Version not changed"
                  exit 1
                  fi

    check-tokens-and-variables:
        needs: check-version
        runs-on: ubuntu-latest
        steps:
            - name: Check NPM Token
              run: |
                  if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
                    echo "NPM_TOKEN is not set"
                    exit 1
                  else
                    echo "NPM_TOKEN is set"
                  fi

    release:
        needs: check-tokens-and-variables
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: simple

    publish-npm:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Publish to NPM
              if: ${{ needs.release.outputs.release_created }}
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
